# Generated by Django 2.2.7 on 2019-11-08 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='management.Brand'),
            preserve_default=False,
        ),
    ]
