# Generated by Django 2.2.7 on 2019-11-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_device_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='remarks',
            field=models.CharField(default=False, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=200),
        ),
    ]
