# Generated by Django 2.2.7 on 2019-12-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20191125_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
